FROM hub.hamdocker.ir/node:18.19.1 AS base

WORKDIR /app

ARG NODE_OPTIONS
ARG NEXT_PUBLIC_WEBSITE_URL
ARG NEXT_PUBLIC_HASURA_API_URL
ARG NEXT_PUBLIC_API_URL_
ARG NEXT_PUBLIC_API_URL
ARG NEXT_PUBLIC_ENVIRONMENT
ARG SENTRY_AUTH_TOKEN
ARG NEXT_PUBLIC_GROWTHBOOK_API_HOST
ARG NEXT_PUBLIC_GROWTHBOOK_CLIENT_KEY
ARG NEXT_PUBLIC_ISR

COPY package.json ./
RUN npm install
COPY . ./
RUN npm run build

CMD npm start
